### ISSUE TITLE
Pretrained model load failure

### ISSUE THREAD

**Issue by amajee11us** [dingmyu/D4LCN#13]
Hi, I tried your code for testing using the pretrained model, but am receiving this error.
Traceback (most recent call last):
  File "scripts/test.py", line 48, in <module>
    load_weights(net, weights_path, remove_module=True)
  File "/data/pri/D4LCN/lib/core.py", line 405, in load_weights
    src_weights = torch.load(path)
  File "/home/archbinder/anaconda3/envs/d4lcn/lib/python3.6/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/archbinder/anaconda3/envs/d4lcn/lib/python3.6/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
MemoryError

I have verified that, I have enough memory to load the model on both CPU and GPU.

**Comment by dingmyu** [comment]
Sorry. We have updated the model. You can download and try again.

Mingyu

**Comment by Shovakar** [comment]
@amajee11us Sir, I tried to run the code. But failed many times. Could you please tell me how to build the code? I am a quite new in this domain. Thank you.
