### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kksgit** [dingmyu/D4LCN#9]
Hi Mingyu,

When I try to train the model, it showed error as below.

`
Traceback (most recent call last):
  File "scripts/train.py", line 213, in <module>
    main(sys.argv[1:])
  File "scripts/train.py", line 118, in main
    iterator, images, depths, imobjs = next_iteration(dataset.loader, iterator)
  File "/home/rhett.wang/pyProjects/D4LCN/lib/core.py", line 604, in next_iteration
    images, depths, imobjs = next(iterator)
  File "/home/rhett.wang/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/rhett.wang/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/rhett.wang/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rhett.wang/local/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/rhett.wang/pyProjects/D4LCN/lib/imdb_util.py", line 234, in __getitem__
    depth = depth[:, :, np.newaxis]
TypeError: 'NoneType' object is not subscriptable
`
I thought it maybe the problem of the version of pytorch.
But I have tried pytorch 1.0/1.1 and cuda 9.0/10.0. The probelm was still there.

Have you met this error before?

**Comment by dingmyu** [comment]
Hi, It seems that the depth file does not exist. Did you download the depth map and put it in the right folder?

Thanks,
Mingyu

**Comment by kksgit** [comment]
Thank you very much! My fault. It works now.

Thanks again for your kindly reply!
